### ISSUE TITLE
Firefox Android

### ISSUE THREAD

**Issue by 00-1** [craftwar/youtube-audio#10]
Is it possible to make this add on available on Firefox for Android?

**Comment by craftwar** [comment]
I tested old version, it works under Android in developer mode (current version is not tested). Mozilla limit installable extension under Android, nothing I can do.

**Comment by craftwar** [comment]
Fixed after Dec 14.

https://blog.mozilla.org/addons/2023/11/28/open-extensions-on-firefox-for-android-debut-december-14-but-you-can-get-a-sneak-peek-today/
