### ISSUE TITLE
The add-on no longer works

### ISSUE THREAD

**Issue by felileg** [craftwar/youtube-audio#12]
Issue:
Over the last few days, all the youtube-audio add-ons have stopped working. I assume that Youtube has changed the way it works, but I don't have the technical skills to say more.

Repro steps:
Try to play any video, even with multiple reloads

Browser: same issue on LibreWolf 119.0.1-1 and Firefox 121.0
OS: Windows 10

**Comment by craftwar** [comment]
this av1 issue?
https://addons.mozilla.org/en-US/firefox/addon/youtube-audio_only/reviews/2033710/

user reports it works
https://addons.mozilla.org/en-US/firefox/addon/youtube-audio_only/reviews/2033710/

My computer doesn't support av1, this extension still works.

Current possible workaround: Change to lower resolution, youtube may stop stream av1 to you.
