### ISSUE TITLE
Autoplay disabled in playlists

### ISSUE THREAD

**Issue by felileg** [craftwar/youtube-audio#13]
Symptom: Automatic playback is disabled. Even if it skips as expected to the next music, you have to manually click to start the sound on each video.

Reproduction: Listening to any playlist, such as a mix, on YT or YT Music.

Setup: Librewolf 119.0.1-1 with Youtube Audio Only 24.1.17

**Comment by craftwar** [comment]
Can't reproduce. This extension doesn't nothing to playlist & autoplay.
More likely setting or some extension changes behavior.

**Comment by craftwar** [comment]
After more testing, I reproduce issue and fix it.
I think youtube may be testing new changes, it delivers different pages to user randomly. That's why extension is not working on every users' environment.
This extension may be dead soon.
