### ISSUE TITLE
Feature Request: Add Thumbnails

### ISSUE THREAD

**Issue by FrancescoDOS** [craftwar/youtube-audio#15]
Hey, thanks for making the extension since the original one doesn't work on Firefox for me. Though I instantly noticed that the thumbnail image was not loaded (black image instead) like in the original extension when playing a video. 

Would that be possible to bring loading thumbnails over from the original?
Or if it was excluded to save more data could it be an option?

**Comment by craftwar** [comment]
I prefer keep this extension simple, I will not add this feature. You can use other similar extension or make your own fork.
BTW, I have not used this extension for long time, I make basic maintenance only.
