### ISSUE TITLE
Feature Request: YouTube Music

### ISSUE THREAD

**Issue by crborga** [craftwar/youtube-audio#2]
I was hoping you could make this work on music.youtube.com as well.

**Comment by craftwar** [comment]
closed in #1

**Comment by crborga** [comment]
Add still play video, is there any way disable that?

Sent from Yahoo Mail on Android 
 
  On Fri, Sep 28, 2018 at 12:00 AM, craftwar<notifications@github.com> wrote:   
closed in #1

**Comment by craftwar** [comment]
Youtube Music is not available in my region. I can't do anything to this.
