### ISSUE TITLE
Sound plays unexpectedly on home page

### ISSUE THREAD

**Issue by felileg** [craftwar/youtube-audio#9]
Hi,
Youtube has a feature that lets you preview a video on the homepage by hovering over it. When doing this, it looks like the extension conflicts with it, and the sound is played twice. Even by moving the pointer, the sound continues and cannot be stopped.
Firefox 117.0.1 / Youtube Audio Only 0.3.10

Otherwise, a thousand thanks for this add-on, which is the only one of its kind to work perfectly, without unnecessary interruptions or reloads!

**Comment by craftwar** [comment]
I make a quick fix to ignore Youtube homepage workaround this issue.
